### ISSUE TITLE
TypeError: Not allowed to define a non-configurable property on the WindowProxy object

### ISSUE THREAD

**Issue by richardgoater** [gaearon/react-transform-hmr#1]
Hi @gaearon, just wanted to say thanks for everything you're working on, really awesome stuff and really pushing things forward!

After trying to run the react-transform-boilerplate, I think I managed to narrow down the component at fault to this transform. The error is occurring in Firefox Developer Edition, version 42, and it seems as though the bundle is prevented from executing completely with the following message:

`TypeError: Not allowed to define a non-configurable property on the WindowProxy object`

This does not occur in Chrome 45. Unfortunately Firefox seems unable to map the eval'd line numbers back to source at all, making debugging pretty difficult...

**Comment by gaearon** [comment]
Thanks! Please reopen if 0.1.4 doesn't solve this issue.

**Comment by mdziekon** [comment]
@gaearon I've also found out about this problem, and I can confirm that it works.
(Actually, I was writing a post with solution, but you were faster than me... :smile: )

**Comment by richardgoater** [comment]
Working for me now, many thanks!
