### ISSUE TITLE
Wrapped components have no setState in IE9

### ISSUE THREAD

**Issue by kentor** [gaearon/react-transform-hmr#12]
Basically wrapped components seem to be missing their `setState` method. Might be an issue with react-proxy and not react-transform-hmr... Tested on IE9. Here's a repo with a minimal repro case: https://github.com/kentor/react-transform-hmr-ie9.

I also get the Warning message "Something is calling a React component directly. Use a factory or JSX instead."

![screen shot 2015-09-22 at 10 28 19 am](https://cloud.githubusercontent.com/assets/240493/10026100/ad5dc4b0-6114-11e5-9be5-5cf4fb239f54.png)

Other info:
- Don't get this issue in Chrome or Firefox.
- Don't think browserify-hmr is the problem. Same thing with webpack using the babel transform.
- Did not get this with react-hot-loader

@gaearon do you know what could cause this on top of your head? if not I can look into it some time tomorrow

**Comment by gaearon** [comment]
That's weird. I'd say look into react-proxy and try to reproduce it there.

**Comment by kentor** [comment]
ok i'll close this and write something there.
