### ISSUE TITLE
Got error: "EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection."

### ISSUE THREAD

**Issue by f15gdsy** [gaearon/react-transform-hmr#14]
Hi, I got this error in browser. Any ideas what it mean?

```
EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.
```

**Comment by gaearon** [comment]
React Transform HMR does not perform any network calls. I think this is the wrong repository to file this issue. Please file it in the project where you can reproduce it—preferably with a sample project.

**Comment by Nase00** [comment]
I ran into this exact error while swapping my configuration from react-hot-reloader to react-transform-hmr. The thing that finally seemed to work was to kill all processes on ports used by my project (On Ubuntu, `sudo kill `sudo lsof -t -i:8080` to kill anything on port 8080), so I'm guessing it was some kind of hanging process. Hope that helps.

**Comment by AlastairTaft** [comment]
I'm getting this in the console too, anyone figured out it's cause? Or got a link to this issue reported elsewhere? This is the first hit on Google

**Comment by sowiecki** [comment]
I received this error on a project that uses Sinatra/Ruby to serve the client. I tried manually setting the MIME type to `text/javascript` and `text/event-stream` on the bundle before serving it, but no luck there

I have another project that uses the same express server to serve the bundle and manage hot reloading, and that one works fine. I suspect this is an issue with compiling the bundle with one server and actually serving it up with another. Which is kind of unavoidable if the backend isn't Node, unfortunately.

**Comment by gaearon** [comment]
> This is the first hit on Google

Doesn't change the fact that it has zero to do with this project. :wink:
You need to see what powers your HMR implementation (e.g. https://github.com/glenjamin/webpack-hot-middleware?) and ask there.

**Comment by AlastairTaft** [comment]
@Nase00 I think you're right, I was running the server on two ports. The hot reloading must of been on the different port.

Not an issue in production, i.e. not using the hot reloader.
