### ISSUE TITLE
HMR without JSX

### ISSUE THREAD

**Issue by ccorcos** [gaearon/react-transform-hmr#15]
What if I'm writing code in coffeescript?

**Comment by ccorcos** [comment]
> The following modules couldn't be hot updated: (Full reload needed)
> - ./src/main.coffee

**Comment by onemanstartup** [comment]
If you are using webpack, use babel at the end of loading.

``` js
      { test: /\.(cjsx|coffee)$/, loaders: ['babel', 'coffee', 'cjsx']},
```

**Comment by gaearon** [comment]
Yeah, right now you'd need to post-process JS with Babel. Unfortunately that won't work for classes defined in CoffeeScript: you'd have to keep using `React.createClass`. A longer term solution is to create a CoffeeScript parser for Babel, or keep using React Hot Loader.

**Comment by ccorcos** [comment]
cool cool. sounds good. no classes is fine with me :)

**Comment by ccorcos** [comment]
Whats the benefit of using ES6 classes? I never understood that. It only seems to overcomplicate things. You end up having to bind your own class methods. And then you need things like decorators instead of just a high-order function on a plain object...
