### ISSUE TITLE
Is there an issue with react-router

### ISSUE THREAD

**Issue by KeKs0r** [gaearon/react-transform-hmr#16]
I started playing around with the counter example of redux and added some things. One of those additions was react router. 

I have also changed some other things, so I am not 100% sure that this is the issue, but I realized that now my hot reloading is not working anymore.

I have also seen that it does not work in the real-world example. 
https://github.com/rackt/redux/issues/832

**Comment by gaearon** [comment]
Let's track it in https://github.com/rackt/redux/issues/832 because the transform is so small and straightforward that, whatever the problem is, it's likely not here.
