### ISSUE TITLE
Firefox issue: TypeError: Not allowed to define a non-configurable property on the WindowProxy object

### ISSUE THREAD

**Issue by MoOx** [gaearon/react-transform-hmr#2]
Since I added this transformation, I am getting this issue on Firefox Nightly, which is completely breaking my rendering (note: works on Chrome and Safari)
Any idea ?

Seems related to
- https://github.com/domenic/window-proxy-spec
- https://esdiscuss.org/topic/figuring-out-the-behavior-of-windowproxy-in-the-face-of-non-configurable-properties
- https://github.com/domenic/window-proxy-spec/issues/4#issuecomment-126566221

I pasted some clues, but to be honest, :dog: "I don't know what I am doing".

**Comment by gaearon** [comment]
This look like duplicate of #1 and I assume this was fixed in 0.1.4.
Please verify.

**Comment by MoOx** [comment]
Oh very sorry for missing this. It's working fine with 0.1.4, thanks !
