### ISSUE TITLE
File/Program node, we can't possibly find a statement parent to this

### ISSUE THREAD

**Issue by johanneslumpe** [gaearon/react-transform-hmr#21]
Trying to integrate this into a project, but the plugin complains that it cannot find parents for certain files. 

@gaearon Is there a certain structure which i need to follow? Do I still need a single top level react component which then imports my routes etc.?

Sorry if this issue does not actually belong here - was not sure whether to post here or on the repo for the babel plugin.

**Comment by gaearon** [comment]
This surely belongs in Babel plugin. :-)
It's a bug. Please attach a minimal reproducing example to the issue.

**Comment by johanneslumpe** [comment]
@gaearon ok cool. I will try to open an issue as soon as I can create a concise example!

**Comment by wind0r** [comment]
This happens if you use optimisation.react.constantElements

**Comment by gaearon** [comment]
Can you still create a specific example?

By the way "constant elements" is a production optimization, do you use it in development?

**Comment by wind0r** [comment]
Just add "optional": [‘optimisation.react.constantElements‘] to your bablerc @ hmr boilerplate example.
I do not use it in development. I added it to bablerc for a production build and found that error.
Defining those optimisations in a webpack module loader would be the right way or?

**Comment by GuillaumeCisco** [comment]
Any news about this issue?
