### ISSUE TITLE
Babel's Class Call Check vs IE10

### ISSUE THREAD

**Issue by dallonf** [gaearon/react-transform-hmr#23]
When running a `react-transform-hmr`-enabled application in IE10, you will get Class Call Check ("Cannot call a class as a function") errors from Babel and React components will fail to render. This seems to occur when calling `React.render` on an ES6 class. This might be a problem in `react-proxy`, but `react-transform-hmr` is as much as I could isolate it.

Note that IE10 is probably _not_ going to support hot loading in most setups (it doesn't support Server-Sent-Events, which at least `webpack-hot-middleware` uses), so this is more of an inconvenience than a blocker; I have to completely turn off HMR and restart the Webpack server to test in IE10, rather than it failing gracefully.

**Comment by gaearon** [comment]
Yeah, please track this in https://github.com/gaearon/react-proxy/issues/27.
