### ISSUE TITLE
Full reload when declaring render as class property arrow function

### ISSUE THREAD

**Issue by confiks** [gaearon/react-transform-hmr#24]
We've been breaking our heads on an issue where a full reload is triggered on a change within the render method of a React component, with the warning: "[HMR] The following modules couldn't be hot updated: (Full reload needed)".

After a lot of fiddling with the source, and stripping it down to the bare basics, we came to the conclusion that using class properties with arrow functions causes the issue. It is reproducible in react-transform-boilerplate with [this simple change](https://github.com/confiks/react-transform-boilerplate/commit/a0c82a90449c00e0ef7a57b24ab57fcb52d38bd1).

In the boilerplate app, the issue only seems to pop up when changing the render function of the root component. In our own app, changing the definition of any function causes a full reload when changing something inside that function.

I'm not so sure that I'm filing this issue on the correct project. Please 302 me if necessary.

**Comment by gaearon** [comment]
Thanks for reporting. Why would you want to bind the render function though? React calls it, so binding it makes no difference (and makes your app slower because you do that for every instance).

**Comment by confiks** [comment]
It's mostly consistency: using a single way to define functions inside a class, without having to spend time thinking about whether it's being called from outside. We also didn't think it'd have any other consequences.

**Comment by gaearon** [comment]
Got it.
Unfortunately Babel plugin won't be able to hot reload them anyway currently.
You can track https://github.com/gaearon/react-proxy/pull/8 in case this limitation changes.
