### ISSUE TITLE
Full page reload instead of hot reload

### ISSUE THREAD

**Issue by hunterbmt** [gaearon/react-transform-hmr#25]
I met this error and have no idea how to solve it. Could you please help me with that ?
[HMR] Cannot apply update. Need to do a full reload!
[HMR] Error: Aborted because 129 is not accepted

**Comment by bebraw** [comment]
@hunterbmt Is it possible for you to push an example to GitHub? It's very hard to debug otherwise.

**Comment by hunterbmt** [comment]
@bebraw I found out the reason, I used https://github.com/davezuko/react-redux-starter-kit and  included react-bootstrap as vendor dependencies (will be compiled to vendor.js). After remove react-bootstrap from vendor dependencies, everything back to normal. I submitted an issue to react-redux-starter-kit :)
