### ISSUE TITLE
react-transform-hmr is being required in jest tests?

### ISSUE THREAD

**Issue by buob** [gaearon/react-transform-hmr#27]
I'm not sure why this might be happening, but I'm getting the following on a new project on the first jest test: 

``` bash
node_modules/react-transform-hmr/lib/index.js: Cannot read property 'type' of null
```

I was confused why react-transform-hmr was even being required for anything, so I took out the react-transform stuff from babelrc and uninstalled the module, but then I got

``` bash
product-preview.jsx: Cannot find module 'react-transform-hmr' 
```

So it seems like it's being explicitly required somewhere/somehow.

Any guidance would be greatly appreciated, thanks so much for the great product!

**Comment by gaearon** [comment]
You're probably running tests without any `NODE_ENV`, so Babel assumes `"development"` and enables it per `.babelrc`.

**Comment by buob** [comment]
I suspected that, so I changed the script to be `NODE_ENV=test jest`, and even got rid of the config in `.babelrc` so it wouldn't have anything to reference react-transform-hmr, but it's still happening.  Even the explicit `export NODE_ENV=test` before running the tests didn't affect it. :confused:

**Comment by gaearon** [comment]
Maybe there's some weird caching going on?
If you removed it from config, where else can it come from?
You can delete the package to be sure, and look what code crashes.

**Comment by gaearon** [comment]
Anyway, this looks like an issue in your setup, rather than an issue with this project.

**Comment by joshblack** [comment]
@buob did you ever resolve this issue? I'm having the same problem when setting up jest with `react-transform-hmr`. Changing `NODE_ENV` doesn't stop the Runtime Error that jest throws, and removing it from `babelrc` also doesn't help. 

If you remove the `react-transform-hmr` module from the `node_modules` folder then it just says that it can't find that module.

**Comment by buob** [comment]
A colleague of mine ended up figuring it out because of this issue - https://github.com/gaearon/react-transform-hmr/issues/5#issuecomment-142429722

We moved our `.babelrc` content to webpack config.

**Comment by obourne** [comment]
I had the same issue and ended up removing .babelrc too but jest didn't stop using react-transform-hmr until I manually deleted the .haste_cache dir from the jest-cli node_modules dir

**Comment by joshblack** [comment]
@obourne that is what tripped me up for the longest time. Thanks for writing it down, I'm sure whoever comes across this issue next will thank you for it.

**Comment by jonaswindey** [comment]
For later versions of Jest, you also have to remove the cache folder configured in jest /"cacheDirectory" in package.json (just wasted 2 hours looking for it)

If you don't specify the cacheDirectory the folder is at `/private/var/folders/lm/x4_bq9sd24d9_vjs84wdl9cr0000gp/T/jest/jest-transform-cache--Users-jonas-Development-3nit-io-aa63b6391f6782d2e445325c13c1bc66` (depending on your environment) , so just put "cacheDirectory": "<rootDir>/jest-cache" under the jest key of your package.json and you'll be able to remove that when necessary.
