### ISSUE TITLE
Full reload needed

### ISSUE THREAD

**Issue by white87332** [gaearon/react-transform-hmr#29]
Hi! I use the redux counter sample to set my project. The react-transform-hmr always send the message "Full reload needed" in browser console. Could you please help me with that ?

![2015-11-03 9 44 47](https://cloud.githubusercontent.com/assets/2655810/10909418/233b7940-8274-11e5-8b37-4bc459542922.png)

My simple project is in https://github.com/white87332/reduxCounter

**Comment by gaearon** [comment]
Rename `_babelrc` to `.babelrc`, that's how it should be called.

**Comment by white87332** [comment]
Thanks! It works!
