### ISSUE TITLE
PhantomJS Hangs

### ISSUE THREAD

**Issue by AdamBrodzinski** [gaearon/react-transform-hmr#31]
I'm having troubles getting PhantomJS to work with the react transform boilerplate. When I run it with Chrome all tests pass but if I run it with Phantom it just hangs with `[HMR] connected`.

Have you ever ran into this before? Any ideas for troubleshooting would be most helpful!

Here's the full debug info if it's helpful:

``` text
acceptance|master⚡ ⇒ be rspec

Randomized with seed 56835
D: [11/05/15 21:31:13][tests] - Executing tests with this configuration:

---
BROWSER: phantomjs
BASE_URL: http://localhost:3000

D: [11/05/15 21:31:13][tests] -
D: [11/05/15 21:31:13][tests] - =============================
D: [11/05/15 21:31:13][tests] - Starting test: Page: Overview should have overview heading
D: [11/05/15 21:31:13][tests] - From file    : ./spec/pages/overview_spec.rb
D: [11/05/15 21:31:13][tests] - -----------------------------
[HMR] connected
D: [11/05/15 21:33:19][tests] -
D: [11/05/15 21:33:19][tests] - -----------------------------
D: [11/05/15 21:33:19][tests] - Completed test: Page: Overview should have overview heading
D: [11/05/15 21:33:19][tests] - From file     : ./spec/pages/overview_spec.rb
D: [11/05/15 21:33:19][tests] - Result        : Fail - RSpec::Core::MultipleExceptionError
D: [11/05/15 21:33:19][tests] - =============================
```

Cheers!

**Comment by gaearon** [comment]
I'm not sure why, but do you really need it with Phantom?
I'd just run it with a different configuration and React Transform disabled.

PS This particular project is just a binding for HMR. It's not an HMR implementation. Take a look at the source—it's unlikely that, whatever issue you have, it's related to this repository.

**Comment by AdamBrodzinski** [comment]
Oh sorry for the lack of context! I was using PhantomJS with Capybara for end-to-end tests. Using the Chrome driver works but flashes a window up every run and is slower.

It just hangs and logs `[HMR] connected` but perhaps it's the webpack dev server that's causing this?

I'll try disabling React Transform to see if that can get it working... it seems like the app never boots up when the PhantomJS driver is loading the page.

Thanks! Much appreciated!!

**Comment by sontek** [comment]
@AdamBrodzinski Did you ever solve your issue?  I'm running into this as well.  I want to run our selenium tests against my local running app to see if they'll pass but it only works with Chrome/Firefox.  Fails with PhantomJS.

**Comment by sontek** [comment]
It seems like its because of the SSE events from webpack hot middleware. Doesn't look like PhantomJS can handle them?

**Comment by AdamBrodzinski** [comment]
@sontek I ended up switching to using Wallaby with Chrome so i'm not sure if this has been resolved. Good luck! 👍
