### ISSUE TITLE
Hot module replacement should trigger render ?

### ISSUE THREAD

**Issue by gobadiah** [gaearon/react-transform-hmr#33]
I have a setup with webpack and react-transform-hmr, I managed to make it work correctly, i.e. when changing a component, I get the expected: 

```
[HMR] bundle rebuilding
[HMR] bundle rebuilt in 1780ms
[HMR] Checking for updates on the server...
[HMR] Updated modules:
[HMR]  - ./src/containers/App.js
[HMR]  - ./src/routes.js
[HMR]  - ./src/bin/client.js
[HMR] App is up to date.
```

However, this doesn't trigger a rerender of the components, therefore making it less useful.

Is that the expected behaviour anyway ? Or am I missing something ?

**Comment by gaearon** [comment]
Please post a complete project that reproduces the issue. [React Transform Boilerplate](https://github.com/gaearon/react-transform-boilerplate) doesn't have it, therefore it's not the expected behavior. It's hard to guess from a few lines of log. :wink:

**Comment by gobadiah** [comment]
Sorry about that, it's not a react-transform-hmr issue, it was a problem with redux-router and the way I implemented it. 

My bad !

**Comment by bunkat** [comment]
@gobadiah What was the problem that you had? I'm running into the same thing where HMR says that modules have been updated but it doesn't actually trigger a rerender of the components.

**Comment by nhll** [comment]
I'm having the same issue: Code changes trigger a rebuild and HMR, but the actual UI doesn't get updated. A JavaScript file containing the updated module is successfully loaded into my browser's source tree, but without any effect on the UI. See the following screenshot:

![HMR Screenshot](http://i.imgur.com/vY3et6j.png)

The [React Transform Boilerplate](https://github.com/gaearon/react-transform-boilerplate) works properly for me, so there must be something wrong with my project. I copied all the relevant configuration from the boilerplate to my project.

I'm not using stateless functional components and I don't have any routing in place.

Any ideas?

**Comment by gaearon** [comment]
@nhll Give [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61) a try, maybe it will work better for you!

**Comment by bpb27** [comment]
Having this problem as well with react 16.2.0 and react-hot-loader 3.1.3. My temporary solution is to pass a random prop into my App component.

```jsx
  const renderApp = () => {
    ReactDOM.render(
      <Provider store={store}>
        <App random={Math.random()}/>
      </Provider>,
      document.getElementById('app')
    );
  }

  if (module.hot) module.hot.accept('./app', renderApp);
```

App is a class (`class App extends Component`) connected to the Redux store (looking for a user), and renders a `<Router>`.
