### ISSUE TITLE
Doesn't work with react-jss

### ISSUE THREAD

**Issue by MaxNamazov** [gaearon/react-transform-hmr#35]
I'm trying to make basic app setup with [react-jss](https://github.com/jsstyles/react-jss) and it doesn't seem to be working with react-transform-hmr, however hmr works well with everything else. Actually, hot-update file is loaded and it contains updated style, but seems that stylesheet is not replaced after.
I use ES6 classes for component definition and ES7 decorator `@useSheet` for applying higher-order react-jss component, if it can help with investigation.
Thnx in advance.

**Comment by gaearon** [comment]
I replied in https://github.com/jsstyles/react-jss/issues/29#issuecomment-192795272.
