### ISSUE TITLE
locals[0] does not appear to be a `module` object...

### ISSUE THREAD

**Issue by micooz** [gaearon/react-transform-hmr#38]
> ...../react-transform-boilerplate/node_modules/react-transform-hmr/lib/index.js:51
>     throw new Error('locals[0] does not appear to be a `module` object with Hot Module ' + 'replacement API enabled. You should disable react-transform-hmr in ' + 'production by using `env` section in Babel configuration. See the ' + 'example in README: https://github.com/gaearon/react-transform-hmr');

I'm trying server-side rendering and I use `react-transform-hmr` to do hot reload, but when I import react components to the script, the error above is thrown.

I followed `react-transform-boilerplate` and simply add a line to the top of the `devServer.js`:

```
var App = require('./src/App');
...
```

then run the script with babel-node:

```
"start": "babel-node devServer.js"
```

and you will see the problem. So how can I use this plugin to do server-side rendering?

**Comment by gaearon** [comment]
Don't enable the `react-transform` plugin when rendering on the server.
It is only meant for the client environment.

**Comment by micooz** [comment]
Got it. Thank you @gaearon. I think I have misunderstood something...

**Comment by mattkrick** [comment]
Just upgraded to the beta & the same error started throwing for me. Is there any other workaround? Perhaps a soft warning instead of error? 
In v1, instead of using ejs or sending a static string or `.html` I made a string out of a react component. As a workaround I can do a series of `string.replace`, but it's not very pretty.

**Comment by gaearon** [comment]
> Is there any other workaround? 

Have you tried the solution described in the error message?

**Comment by mattkrick** [comment]
I copied the `.babelrc` from the react-transform boilerplate & explicitly set `NODE_ENV=development`, but still no luck.

**Comment by andrewcoelho** [comment]
FWIW I'm encountering the same issue as @mattkrick

**Comment by andrewcoelho** [comment]
My experience is the same as @micooz. You say "Don't enable the react-transform plugin when rendering on the server". Does this mean the plugin can't be used with a universal app?

**Comment by CrocoDillon** [comment]
I moved the react-transform stuff from `.babelrc` to `webpack.config.js` as query.

``` javascript
{
  test: /\.jsx?$/,
  loader: 'babel',
  query: {
    plugins: [
      ['react-transform', {...}]
    ]
  }
}
```

That way you can still use react-transform. If someone knows a better solution please do tell. I’d have liked keeping that in `.babelrc` as much as possible.

**Comment by micooz** [comment]
@andrewcoelho Yes, it can. Just do as @CrocoDillon said.
Here is an another example:
https://github.com/erikras/react-redux-universal-hot-example/blob/master/webpack/dev.config.js#L67

Notice that `'babel?' + JSON.stringify(babelLoaderQuery)` in webpack configuration avoids react-transform working at server side.

You can use [piping](https://github.com/mdlawson/piping) or other techniques to do server side reload.

**Comment by mxstbr** [comment]
I'm getting this error on the client side after building my application and uploading it to my web server. Works perfectly fine in dev mode, but throws the error when deployed.

[This](https://github.com/mxstbr/login-flow/blob/master/.babelrc) is the `.babelrc` file, and [here](http://loginflow.mxstbr.com) is the deployed website. (Won't show anything because of the error)

I am using `env` in the `.babelrc`, and I've tried moving the config to the `package.json` and using `query` in the webpack config like @CrocoDillon, but that didn't solve the problem. Any ideas?

EDIT: This is the command that's run when building: `NODE_ENV=production && webpack --config webpack.prod.config.js --progress --colors -p`, I've also tried setting `BABEL_ENV`, but that didn't work either.

**Comment by gaearon** [comment]
@mxstbr Are you sure `&&` is needed in this command?

**Comment by mxstbr** [comment]
@gaearon Good tip, but that didn't work, still getting the same error.

**Comment by CrocoDillon** [comment]
@mxstbr, how do you start your server in production?

**Comment by gaearon** [comment]
@mxstbr 

It worked for me with your repo.
Are you sure you're not hitting a cached JS file?

```
NODE_ENV=production webpack --config webpack.prod.config.js --progress --colors -p
```

builds a file with no mentions of `react-transform` in it.

**Comment by mxstbr** [comment]
@CrocoDillon `npm run build`, which creates a `build` folder, the contents of which I upload to my build server.

@gaearon That is interesting! Does it work for you on http://loginflow.mxstbr.com ?

**Comment by CrocoDillon** [comment]
@mxstbr for me it doesn't work either on your live version, so if it's cache it might be CloudFlare's. See headers:

```
Cache-Control:public, max-age=2592000
CF-Cache-Status:HIT
```

**Comment by gaearon** [comment]
@mxstbr It's probably cached.. somewhere. Or your upload script might have a bug. I get a different JS file when I build locally.

**Comment by CrocoDillon** [comment]
On-topic, for SSR I found an alternative to moving all transform related stuff from `.babelrc` to `webpack.config.js`, which is ignoring the `.babelrc` file when using babel-register (perhaps there is a similar option in babel-node).

You can see an example [here](https://github.com/CrocoDillon/universal-react-redux-boilerplate/commit/b2c3bc2b678e62a8e493a6567dca827f29360c26#commitcomment-14987978), but sadly it's currently ignored. Hope the team behind Babel accepts my PR which works for me, babel/babel#3168.

**Comment by mxstbr** [comment]
@CrocoDillon it was the CloudFlare cache, and @gaearon's tip of removing the `&&` in the command fixed the problem!

Thanks so much for the help! :+1:

**Comment by Dindaleon** [comment]
I am having the same issue since updating babel to version 6. The config inside webpack is being ignored and putting it inside a .babelrc throws that error.

```
throw new Error('locals[0] does not appear to be a `module` object with Hot Module ' + 'replacement API enabled. You should disable react-transform-hmr in ' + 'production by using `env` section in Babel configuration. See the ' + 'example in README: https://github.com/gaearon/react-transform-hmr');
^

Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration.
```

**Comment by gaearon** [comment]
1.x won't work with Babel 6, this is expected. 
Please use 2.0 beta. It's on NPM.

**Comment by gaearon** [comment]
Meaning 2.0 of Babel plugin. Not this repo.

**Comment by anorudes** [comment]
@gaearon Where i can get 2.0 beta verison of "react-transform-hmr"?
npm version have only:
[ '0.1.5', '0.1.6', '1.0.0', '1.0.1' ]

**Comment by hnqlv** [comment]
For anyone using Z or Fish shell. For some reason passing the `'process.env.NODE_ENV': JSON.stringify('production')` in the webpack isn't working for me. I got it working by running `env NODE_ENV="production" webpack --confing webpack.config.production.js"`.

**Comment by gaearon** [comment]
I don’t see anything actionable here so closing.

**Comment by gaearon** [comment]
None of this should matter in React Hot Loader 3.
I know React Transform has been a configuration hell; hopefully, this should be solved.
See https://github.com/gaearon/react-hot-boilerplate/pull/61 if you’d like to try it!

**Comment by PhoenixFEC** [comment]
> Don't enable the react-transform plugin when rendering on the server.
> It is only meant for the client environment.

@gaearon I want to disable it, but I don't know how to try it. I holp you help.

I have a `.babelrc` file, and content like this:
{
  "presets": ["react", "es2015"],
  "env": {
    "development": {
        "presets": ["react-hmre"],
      "plugins": [["react-transform", {
        "transforms": [{
          "transform": "react-transform-hmr",
          "imports": ["react", "react-dom"],
          "locals": ["module"]
        }]
      }]]
    }
  }
}

Best Regards.

**Comment by gaearon** [comment]
@PhoenixFEC Have you looked into this solution? https://github.com/gaearon/react-transform-hmr/issues/38#issuecomment-164359991

**Comment by PhoenixFEC** [comment]
@gaearon Yes, and I try to manually changed `env.development` to `evn.production` in `.babelrc` yet. successful.
I think... Does it have otherwise dynamic way to configure in code.
And I try to set some plugin like below, but I failed.

new webpack.DefinePlugin({
        'process.env': {
          NODE_ENV: JSON.stringify('production')
        }

## })

I did. @gaearon Thank you very much. 
Through a variable to configure development or production environment module loaders

**Comment by gaearon** [comment]
@PhoenixFEC Anyway, I recommend you to stop using `react-transform` and look into using [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61) instead.
