### ISSUE TITLE
Requiring unknown module "react-transform-webpack-hmr"

### ISSUE THREAD

**Issue by adampash** [gaearon/react-transform-hmr#4]
Hey, first, thanks for all of your great projects! They've saved me so much time, and I've learned a ton from them.

So, onto the issue:

I've been transitioning various projects from react-hot-loader to react-transform-webpack-hmr, and it's gone without a hitch on React web projects. I've been trying it out on my react-native projects, where I'm running react-native-webpack-server. I followed your basic instructions in [this issue](https://github.com/mjohnston/react-native-webpack-server/issues/55), along with the boilerplate setup, but for some strange reason, I always get this error in the iOS simulator:

> Requiring unknown module "react-transform-webpack-hmr"
> 
> <unknown>
> http://localhost:8080/index.ios.bundle:23569
> ...

<img width="374" alt="screenshot_9_15_15__1_58_pm" src="https://cloud.githubusercontent.com/assets/64131/9885174/d5e232c6-5bb1-11e5-8e3c-b7e2de10f3a2.png">

I realize that I'm very likely barking up the wrong tree (and I apologize if that's the case), but I've tried working around this from every angle I can think of, so I wanted to see if this is something you've seen before and whether there's a fix I'm not aware of.

Again, thank you for all your work!

Update: I should note the obvious: I do have the module installed, and I've removed and re-installed it several times, and likewise restarted the packager, just to sanity check myself.

**Comment by gaearon** [comment]
Can you please provide a project reproducing this so I could take a look? Thanks!

**Comment by adampash** [comment]
Hey Dan,

Here's the boilerplate:

https://github.com/adampash/react-native-redux-starter/tree/react-transform-webpack-hmr

The readme should give you a quick copy/paste for bootstrapping everything. I'm also wondering if something is going wrong w/my node installation, but I've tried different versions of iojs with nvm and I'm getting the same results. Thanks for any help!

**Comment by adampash** [comment]
I haven't updated the code in my project, but I tested your update in [this pull request](https://github.com/mjohnston/react-native-webpack-server/pull/64) and that's working for me, so I'm closing. Thanks again for looking into this! The .babelrc caching had really destroyed my troubleshooting brain.

**Comment by gaearon** [comment]
Thanks for getting me to look into it! Yes, the issue was likely due to https://github.com/mjohnston/react-native-webpack-server/issues/63 and https://github.com/facebook/react-native/issues/1924#issuecomment-120170512.
