### ISSUE TITLE
Changing state does hot reload

### ISSUE THREAD

**Issue by gkiely** [gaearon/react-transform-hmr#41]
Node: 5.3.0
presets: ["react", "es2015", "stage-0"],

```
class App extends Component {
  state = {msg: "myMsg"}

  render() {
    return (
      <div>
        <h1>{this.state.msg}</h1>
      </div>
    );
  }
}
```

Changing myMsg does not hotreload, mapping it to a variable outside the class does.

**Comment by gaearon** [comment]
It can't hot reload changes to the _initial_ state. Don't forget this property assignment is equivalent to setting the field inside the constructor. Even if you change the constructor, the field has already been set. Constructor doesn't run twice. So this is not supported.

**Comment by gkiely** [comment]
Ahhh I thought this might be the case, out of curiosity would it be possible to unmount and remount the component to get this to work? I don't know enough about react yet to know whether or not this is possible.

**Comment by gaearon** [comment]
Maybe. You can track https://github.com/gaearon/react-proxy/issues/15 for that.
