### ISSUE TITLE
Not working with material-ui

### ISSUE THREAD

**Issue by goofansu** [gaearon/react-transform-hmr#43]
When changing a file with material-ui components, hmr didn't happen.

FYI, files following

index.jsx

```
import React from 'react'
import { render } from 'react-dom'

import injectTapEventPlugin from 'react-tap-event-plugin';
injectTapEventPlugin();

import Hello from './components/hello'
render(<Hello />, document.getElementById('root'))
```

hello.jsx

```
import React from 'react'
import RaisedButton from 'material-ui/lib/raised-button'

class Hello extends React.Component {
  render() {
    return <RaisedButton label="submit" />
  }
}

export default Hello
```

.babelrc

```
{
  "presets": ["react", "es2015"],
  "env": {
    // this plugin will be included only in development mode, e.g.
    // if NODE_ENV (or BABEL_ENV) environment variable is not set
    // or is equal to "development"
    "development": {
      "plugins": [
        // must be an array with options object as second item
        ["react-transform", {
          // must be an array of objects
          "transforms": [{
            // can be an NPM module name or a local path
            "transform": "react-transform-hmr",
            // see transform docs for "imports" and "locals" dependencies
            "imports": ["react"],
            "locals": ["module"]
          }]
          // by default we only look for `React.createClass` (and ES6 classes)
          // but you can tell the plugin to look for different component factories:
          // factoryMethods: ["React.createClass", "createClass"]
        }]
      ]
    }
  }
}
```

webpack.config.js

```
var path = require('path');
var webpack = require('webpack');

module.exports = {
  devtool: 'cheap-module-eval-source-map',
  entry: [
    'webpack-dev-server/client?http://localhost:8080',
    'webpack/hot/only-dev-server',
    './public/index'
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/static/'
  },
  plugins: [
    new webpack.NoErrorsPlugin()
  ],
  module: {
    loaders: [{
      test: /\.jsx?/,
      loaders: ['babel'],
      include: path.join(__dirname, 'public')
    }]
  },
  resolve: {
    extensions: ["", ".js", ".jsx"]
  }
};
```

**Comment by gaearon** [comment]
I don't see [`new webpack.HotModuleReplacementPlugin(),`](https://github.com/gaearon/react-transform-boilerplate/blob/3b16558a4cbd3c12939328800b45840df31bef93/webpack.config.dev.js#L17) in your config.

**Comment by gaearon** [comment]
I'm closing but I'll be happy to reopen if you publish a project reproducing the problem and instructions to reproduce it. It's hard to help on issues without a repro case.

**Comment by goofansu** [comment]
I'm using the command "webpack-dev-server --hot" instead, so I think there is no
need to use this plugin, am I right?

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.4.15&pv=9.2&source=email_footer_2]
On 周二, 12月 29, 2016 at 12:16 下午, gaearon/react-transform-hmr
reply@reply.github.com
wrote:
I don't see new webpack.HotModuleReplacementPlugin(),
[https://github.com/gaearon/react-transform-boilerplate/blob/3b16558a4cbd3c12939328800b45840df31bef93/webpack.config.dev.js#L17] in your config.

—
Reply to this email directly or view it on GitHub
[https://github.com/gaearon/react-transform-hmr/issues/43#issuecomment-167715837] .[https://github.com/notifications/beacon/ABFxl6z11ummYCnJp0xdQ1qT9POTDSnSks5pUgC7gaJpZM4G8Jxy.gif]

**Comment by goofansu** [comment]
@gaearon Tested in `react-transform-boilerplate`, it's ok.  I'll check my configs. Thanks

**Comment by gaearon** [comment]
Thanks! `--hot` is a tricky beast, I always forget what exactly it does.
