### ISSUE TITLE
"extra" doesn't exist with babel@6

### ISSUE THREAD

**Issue by MoOx** [gaearon/react-transform-hmr#45]
So I guess doc should be updated?

**Comment by butsjoh** [comment]
I am also wondering about this. The readme on the page says it could be used with the extra option. I am interested in knowing how to use react-transform-hmr in context of the babel-plugin-react-transform. Especially when using webpack. I am trying the following but it fails with the extra error in my development.config file in webpack (instructions from  babel-plugin-react-transform):

```
...

config.module.loaders[0].query.plugins.push('react-transform');
config.module.loaders[0].query.extra = {
  'react-transform': [{
    target: 'react-transform-hmr',
    imports: ['react'],
    locals: ['module']
  }],
  'react-transform-catch-errors': [{
    target: 'react-transform-catch-errors',
    imports: ['react', 'redbox-react']
  }]
};
```

My goals was to avoid the .babelrc file and configure the transforms with the babel-loader.
So is it not possible todo the above and not have a .babelrc file? Is this an issue of react-transform-hmr or rather of the babel-loader?

**Comment by butsjoh** [comment]
Ok seems to have figured it out :) see https://github.com/gaearon/babel-plugin-react-transform/issues/46#issuecomment-152783885

For babel 6 you can just add it to the plugins of the bundle-loader.

```
config.module.loaders[0].query.plugins.push(['react-transform', {
  'transforms': [
    {
      'transform': 'react-transform-hmr',
      'imports': ['react'],
      'locals': ['module']
    },
    {
      'transform': 'react-transform-catch-errors',
      'imports': ['react', 'redbox-react']
    }
  ]
}]);
```

**Comment by gaearon** [comment]
Yep, config format changed with Babel 6 and `2.x` of the plugin.
