### ISSUE TITLE
File depth limit

### ISSUE THREAD

**Issue by inyono** [gaearon/react-transform-hmr#46]
Is there a depth limit for files that trigger a webpack rebundling? In our project, we have a rather deep file structure. E.g., `common/components/App/index.js` triggers rebundling, but `common/components/icons/Icon/index.js` does not.

**Comment by jamiebuilds** [comment]
It's highly unlikely that it has anything to do with your file structure. I'm going to take a wild guess the your icon component is a functional component which is not supported

**Comment by inyono** [comment]
Yeah it is. But `common/components/App/index.js` is so, too, but renders a rebundling nevertheless. Or could it be that rebundling works because we use a non-functional component in `App`?

Edit: I changed App to

```
const App = ({ children }) => (
  <div></div>
);
```

and it also triggers rebundling, at least.

Edit2: Maybe I should clarify: the functional component `App` throws `[HMR] The following modules couldn't be hot updated: (Full reload needed)` but webpack rebundles at least. `Icon` on the other hand does no webpack rebundling at all, i.e. we need to restart the whole dev server to see changes, a reload is not enough.

**Comment by inyono** [comment]
Sorry, nevermind, it works now. -.-

Edit: Seems like the reason for the problem were [not enough watchers](https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#not-enough-watchers)
