### ISSUE TITLE
Hot Reload Electron

### ISSUE THREAD

**Issue by rgbkrk** [gaearon/react-transform-hmr#49]
Do you think there's a way to use this with Electron, without Browserify or Webpack, relying on the `chrome-remote-interface`? That's what [electron-hot](https://github.com/cabul/electron-hot) uses, which works quite well for pure functions. About to try it with React.

**Comment by Macil** [comment]
Chrome's debugging interface works pretty differently than the hot module replacement API used in react-transform-hmr. [Here's a good discussion about the differences.](https://github.com/caspervonb/amokify/issues/3) react-transform-hmr would be unlikely to support it directly. [react-proxy](https://github.com/gaearon/react-proxy) (which react-transform-hmr uses) might be useful for a project doing this though.

**Comment by rgbkrk** [comment]
Well hot damn, [`amok`](https://github.com/amokjs/amok) is cool.

**Comment by gaearon** [comment]
Also https://github.com/geowarin/electron-hot-loader/ for a project that uses `react-proxy` with Electron.

**Comment by rgbkrk** [comment]
Thanks @gaearon!
