### ISSUE TITLE
Class properties do not hot reload ?

### ISSUE THREAD

**Issue by Elyx0** [gaearon/react-transform-hmr#51]
In the context of a `export default class Random extends React.Component {`

With 

``` javascript
    render() {
      return(
        {this.renderTest()}
        {this.renderTest3()}
     );
   }
```

``` javascript
    renderTest()
    {
      return <Button>I will hot reload</Button>;
    }
```

Works for hot reloading but

``` javascript
    renderTest3 = () => {
      return <Button>I will fail.</Button>;
    };
```

Will never get hot reloaded when changing the string. Is it a desired behavior ?

We get the `[React Transform HMR] Patching Builder
 process-update.js?e13e:75 [HMR] Updated modules:
process-update.js?e13e:77 [HMR]  - ./app/components/Random.jsx
 process-update.js?e13e:82 [HMR] App is up to date.`

And the corresponding webpackHotUpdate gets fetched, but the page stays the same.

.babelrc plugins:

```
"presets": ["stage-0","react", "es2015"],
  "plugins": [
    "syntax-class-properties",
    "syntax-decorators",
    "syntax-object-rest-spread",
    "transform-class-properties",
    "transform-decorators-legacy",
    "transform-object-rest-spread",
  ]
```

versions:

```
    "babel-plugin-react-transform": "^2.0.0",
    "babel-plugin-transform-class-properties": "^6.3.13",
    "babel-plugin-transform-decorators": "^6.3.13",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-classes": "^6.3.15",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.3.16",
    "babel-plugin-transform-object-rest-spread": "^6.3.13",
```

Could it be because it's a stage0 feature according to https://github.com/jeffmo/es-class-fields-and-static-properties ?

**Comment by gaearon** [comment]
Please see https://github.com/gaearon/react-proxy/pull/8#issuecomment-142920524.

**Comment by gaearon** [comment]
Technically we can make this work if there is enough interest and the spec stays the same. Let's wait a few more months and see.

**Comment by Elyx0** [comment]
Thanks for your input, I will follow it closely :+1:
