### ISSUE TITLE
Unpatched `react-proxy` dependency breaks React Native build

### ISSUE THREAD

**Issue by jevakallio** [gaearon/react-transform-hmr#55]
The latest stable release of React Native packager is broken due to the `react-transform-hmr`'s transitive dependency [react-deep-force-update](https://github.com/gaearon/react-deep-force-update) including a Babel 6 incompatible `.babelrc` file in the npm package. (See https://github.com/facebook/react-native/issues/5393)

This dependency is already fixed upstream at [`react-proxy@1.1.2`](https://github.com/gaearon/react-proxy/releases/tag/v1.1.2). 

In order to fix the issue downstream at React Native, I believe we will need a new release that updates this dependency. I am not deep enough into this library to be able to safely make and test this upgrade. I will submit a PR for convenience, but would appreciate if a maintainer could weigh in.

**Comment by jevakallio** [comment]
Opened https://github.com/gaearon/react-transform-hmr/pull/56

**Comment by gaearon** [comment]
Fixed.
