### ISSUE TITLE
Add a troubleshooting section

### ISSUE THREAD

**Issue by RaitoBezarius** [gaearon/react-transform-hmr#59]
I saw that React Hot Loader had a troubleshooting section, why not do one with it also?

One thing that would have helped me a lot is that:
### If Webpack throws an error when you reload the page after doing an edition

It means that you didn't add `locals: ['module']` in the Webpack config of `react-transform-hmr`.

I could contribute if you would like or send a PR!

**Comment by gaearon** [comment]
Please send PRs to https://github.com/gaearon/react-transform-boilerplate#faq, that’s where we try to contain them for now.
