### ISSUE TITLE
Does react-transform-hmr support pure function components

### ISSUE THREAD

**Issue by dlmanning** [gaearon/react-transform-hmr#6]
I'm not having any luck getting components defined as a pure function to hot-reload. The component in question:

``` javascript
export default function Light (props) {
  const { light, toggleLight, id } = props
  const status = light.state.on ? 'one' : 'off'

  return (
    <div>{light.name}
      <button onClick={() => toggleLight({ ...light, id })}>
        {status}
      </button>
    </div>
  )
}
```

I get this error in the console:

```
[HMR] Updated modules:
(index):25734 [HMR]  - ./app/components/light.js
(index):25734 [HMR]  - ./app/components/lights.js
(index):25739 [HMR] App is up to date.
(index):15049 Uncaught TypeError: Cannot read property '__reactAutoBindMap' of null
```

Is this scenario supposed to work? Any idea what I'm doing wrong? Let me know if more context is needed.

**Comment by gaearon** [comment]
Not currently.

https://github.com/gaearon/react-proxy/issues/12
https://github.com/gaearon/babel-plugin-react-transform/issues/17

If you'd like to work on this let me know :-)

**Comment by dlmanning** [comment]
@gaearon : Thanks! I'll look into it and try to evaluate whether I have the time to dig into that.

Also wanted to say that everyone on my team really appreciates the work you've done for the community this year. Thanks! You've made all of our jobs easier and more fun.

**Comment by eriknyk** [comment]
something similar here,
but the message is:
```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
processUpdate.js:60 [HMR]  - ./src/components/admin/Blank.jsx
processUpdate.js:91 [HMR] Reloading page
```

**Comment by SpainTrain** [comment]
> You've made all of our jobs easier and more fun.

Not on his team, but :+1: that

**Comment by ghost** [comment]
@gaearon I'd like to work on this. I'm about to start transitioning almost all of our components over to pure components so this would be handy :)

**Comment by onemanstartup** [comment]
@gaearon will it be possible with that to hot-reload component when changing getDefaultProps?

**Comment by gaearon** [comment]
> will it be possible with that to hot-reload component when changing getDefaultProps?

I'm a bit confused—how are default props related to pure function components?

@danmartinez101 

> I'd like to work on this. I'm about to start transitioning almost all of our components over to pure components so this would be handy :)

I have some preliminary work in a branch, give me a few days and I'll try to push something to get started.

**Comment by onemanstartup** [comment]
@gaearon dunno :) I just wanted the feature and wanted to ask. When component pure and you change getDefaultProps it is not reloaded :(

**Comment by gaearon** [comment]
@onemanstartup 

We don't currently support pure components at all. If it works for you, it's probably by accident. This is what this issue is about. :wink:

I'm also not sure what `getDefaultProps` is. For pure components, as well as for ES6 classes, there is no `getDefaultProps()`—only static `defaultProps`.

**Comment by wmertens** [comment]
Just pointing out for interested parties that current development of this feature is happening in https://github.com/gaearon/babel-plugin-react-transform/pull/34 - it's already mostly working it seems.

**Comment by gaearon** [comment]
Please track this in https://github.com/gaearon/babel-plugin-react-transform/issues/57.

**Comment by gaearon** [comment]
React Hot Loader 3 supports functional components without destroying the state.
It supersedes both React Hot Loader and React Transform, and is built on lessons learned from both.
Check it out: https://github.com/gaearon/react-hot-boilerplate/pull/61

**Comment by linus-amg** [comment]
hi @gaearon awesome project, congratulations. though im not developing with react i got inspired to use hmr in a backbone project i've got, im using gulp + rollupify + babelify + hbsfy + browserify + browserify-hmr plugin, now i wanted to see how i could implement a transform to re-render my views or templates, would you know of an easier starting point then react-transform-hmr?
