### ISSUE TITLE
README example for React Native won't work for Babel 5

### ISSUE THREAD

**Issue by catamphetamine** [gaearon/react-transform-hmr#60]
It has that "extra" option which is removed from Babel 6.

**Comment by gaearon** [comment]
Please send a PR to fix it. Thanks!

**Comment by catamphetamine** [comment]
I won't because I don't know how it works.
Anyway, my job was just to inform you of that bug.
I'm not affiliated with React Native in any way.
Closing this.

**Comment by gaearon** [comment]
You can see the updated config just above in the README.
The config below needs to be updated to match the same format.

It is still an issue so I will leave it open.
Thanks for your help!

**Comment by catamphetamine** [comment]
@gaearon The code above is for `.babelrc` configuration.
Is there no way to configure this thing in babel loader query now?

**Comment by gaearon** [comment]
Loader query format has always matched babelrc format exactly. You can take a look at README history to see how earlier version matched.

**Comment by catamphetamine** [comment]
@gaearon ok, I guess I got it working.
Will make a PR.

``` javascript
javascript_loader.query =
{
    plugins:
    [
        [
            'react-transform',
            {
                transforms: 
                [{
                    "transform" : "react-transform-catch-errors",
                    "imports"   : ["react", "redbox-react"]
                },
                {
                    transform : 'react-transform-hmr',
                    imports   : ['react'],
                    locals    : ['module']
                }]
            }
        ]
    ]
}
```
