### ISSUE TITLE
HMR running with no errors but interface not updating

### ISSUE THREAD

**Issue by BenjaminRCooper** [gaearon/react-transform-hmr#62]
I have the following Universal project and I have integrated HMR and it seems to be working. Only problem is the HMR runs fine, no errors are returned, styles can update fine, but when I try to change content in a container or child component, the interface doesn't update. HMR runs, but the new content isn't injected.

Is it possible you could see if I have any issues occuring?

https://github.com/BenjaminRCooper/isomorphic-boilerplate

**Comment by okcoker** [comment]
Running into the same problem. I haven't gotten to look into it but could it be due to `babel-core/register` somehow?

**Comment by gaearon** [comment]
``` js
  "env": {
    "plugins": [["react-transform", {
        "transforms": [{
            "transform": "react-transform-hmr",
            "imports": ["react"],
            "locals": ["module"]
        }]
    }]]
  }
```

is not a correct configuration. You are missing the actual environment name—babel thinks `plugins` _is_ the environment variable you meant. So it completely skips `react-transform` in your config.

You probably want something like 

``` js
  "env": {
    "development": { // <--------- don't forget the actual env name
      "plugins": [["react-transform", {
          "transforms": [{
              "transform": "react-transform-hmr",
              "imports": ["react"],
              "locals": ["module"]
          }]
      }]]
    }
  }
```

instead.
