### ISSUE TITLE
Uncaught ReferenceError: document is not defined

### ISSUE THREAD

**Issue by mtford90** [gaearon/react-transform-hmr#64]
So I just tried to integrate this with rnws and am now seeing the following in the chrome debugger:

```
debuggerWorker.js:18 Uncaught Error: Uncaught ReferenceError: document is not defined
messageHandlers.executeApplicationScript    @   debuggerWorker.js:18
onmessage   @   debuggerWorker.js:33
```

Is this a known issue? I'm guessing it's something to do with this: https://github.com/mjohnston/react-native-webpack-server/issues/103, but that dates all the way back to 0.12. And everything works fine with chrome debugging w/o transform-hmr.

If this is a new one I can try piece together a sample repo from my current project.

**Comment by satya164** [comment]
@mtford90 React Native packager will soon support HMR. You shouldn't need to use third party packagers - https://github.com/facebook/react-native/issues/5338

**Comment by mtford90** [comment]
@satya164 aha, cheers buddy
