### ISSUE TITLE
Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled

### ISSUE THREAD

**Issue by ahmed1490** [gaearon/react-transform-hmr#66]
Setup done with `react-hmre` preset with hapi js.

Example config setup: http://www.webpackbin.com/Ey_d9Jong 

Screenshot of the error:
<img width="1265" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/13687482/d90c91b2-e71b-11e5-83b7-fbba0db045d9.png">

I did add HotModuleReplacement as mentioned here: https://github.com/danmartinez101/babel-preset-react-hmre/issues/16#issuecomment-185885789

Am I missing something?

**Comment by gaearon** [comment]
Using the search [might help](https://github.com/gaearon/react-transform-hmr/issues?q=is%3Aissue+locals+does+not+appear+is%3Aclosed) in the future :wink: .

This plugin should not be enabled on the server. Use `NODE_ENV` (or `BABEL_ENV` to be more specific) to control whether the plugin is active. It corresponds to `env` field in your `.babelrc`.

**Comment by ahmed1490** [comment]
Sorry, but I did read that. And if you missed to see the link of the code the .babelrc looks like this,

```
{
  "presets": ["es2015", "react"],
  "plugins": ["transform-object-rest-spread"],
  "env": {
    "development": {
        "presets": ["react-hmre"]
    }
  }
}
```

Is there something more expected? Thank you for responding so quick :)

**Comment by gaearon** [comment]
Your config says "enabling the plugin when NODE_ENV or BABEL_ENV is set to `development`". The problem likely is that this value is the default. Babel docs say that if you don't explicitly specify those variables, it will assume `development`.

You probably launch the server without any environment at all. So you get `development` by default. If you use something like `BABEL_ENV=server npm start` you will avoid this problem. 

Does this help?

**Comment by m3talsmith** [comment]
This is not closed. I'm having the same issue. I've tried every suggestion in the issues @gaearon and still get the same kind result as @ahmed1490 

```
Uncaught Error: locals[0] does not appear to be a `module` object with Hot Module
replacement API enabled. You should disable react-transform-hmr in production by
using `env` section in Babel configuration. See the example in README:
https://github.com/gaearon/react-transform-hmr
```

This is on my local machine `NODE_ENV=local node server.js`

Using `^1.0.1`

**Comment by ahmed1490** [comment]
I am sorry to respond late.
I was infact running with NODE_ENV=development.

Eventually something worked for me..
I moved the setting to my webpackconfig.dev.js.
with.. following loading config..

```
    module: {
        loaders: [{
            test: /\.js$/,
            exclude: /node_modules/,
            loader: 'babel',
            query: {
                presets: ["react-hmre"]
            }
        }
....
```

and I maintain other babel related config in .babelrc

```
{
  "presets": ["es2015", "react"]
}
```

This worked for me but I haven't yet tried the @gaearon suggestion. I will try once I am back from holidays.

PS: tbh, I havn't really got my head around this. If I say to babel its a 'server' environment, how will babel even use `react-hmre` in my development environment. I need it in my server development env and infact my server uses the babel compiler in `app.use`.
At first glance, one would say it should exclude that as 'react-hmre' is really put in the 'development' env. 
I am just confused.

**Comment by gaearon** [comment]
None of this should matter in React Hot Loader 3.
I know React Transform has been a configuration hell; hopefully, this should be solved.
See https://github.com/gaearon/react-hot-boilerplate/pull/61 if you’d like to try it!
