### ISSUE TITLE
chrome-devtools://devtools/ used as origin for CSS url() in Chrome and Firefox

### ISSUE THREAD

**Issue by ghost** [gaearon/react-transform-hmr#67]
I have this interesting issue which I believe is originating in `react-transform-hmr` or one of its dependencies. I originally thought it might be an issue with Chrome and reported it [there](https://bugs.chromium.org/p/chromium/issues/detail?id=591123), but seeing it also happen in Firefox made me suspect this is related to a hmr module. Interestingly, the issue is not present in Safari.

Here is a test endpoint running `webpack-dev-server` with `react-transform-hmr` exhibiting the issue: [http://52.86.248.16:8080](http://52.86.248.16:8080). Opening the same site in Safari will show the dialog background image correctly, while its url in both Chrome and Firefox will have an origin set to `chrome-devtools://devtools/`.

I haven't confirmed if this happens for all `url()` or just some.

**Comment by gaearon** [comment]
This project is getting deprecated, so you can try better luck with [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61). If you still have the issue, try disabling it (just the loader, not WebpackDevServer or HMR which is a Webpack feature), and see whether it is indeed one of its dependencies. Without a reproduction case, I can’t really help, and in any way I don’t have intention to fix this in this project so I’m closing. Thanks!
