### ISSUE TITLE
Source patching is not working

### ISSUE THREAD

**Issue by marcelaraujo** [gaearon/react-transform-hmr#68]
If you have this source

```
import React from 'react';

export default class Item extends React.Component {
    update(e) {
        console.warn(e.target.value);
    }

    test = (e) =>  {
        console.log("test", e.target.value);
    }

    render() {
        return <span>{this.props.name}<br/>
<input type="text" onChange={(e)=>this.update(e)} /><br/>
<input type="text" onChange={this.test} />
</span>;
    }
}
```

Any change you did on `update` method, the patch works but it doesn't on `test` method which uses arrow function.

**Comment by gaearon** [comment]
ES7 property syntax for functions is not currently supported for hot reloading.
You can track (or better, help implement!) this support in https://github.com/gaearon/react-hot-loader/issues/242.
React Hot Loader 3 supersedes this project.

**Comment by marcelaraujo** [comment]
Thank you.
