### ISSUE TITLE
HMR works intermittently

### ISSUE THREAD

**Issue by ghost** [gaearon/react-transform-hmr#69]
I noticed a really strange behavior of HMR. Sometimes it works for all React components, sometimes for some React components and sometime not at all. I do not know what is the cause. It might be my configuration, so please take a look at my configuration. I do not see there any errors regarding HMR, so it might be also a bug.

The link to my repo:
https://github.com/tommyJS/react-relay-redux-wordpress

The project is under development, so please forgive me lack of extensive description, however, you can easily find settings regarding HMR in the repo.
Cheers.

**Comment by gaearon** [comment]
Please provide specific instructions to reproduce.

**Comment by ghost** [comment]
There are no specific instructions to reproduce the issue. HMR sometimes just works and sometimes not. I noticed that especially when I hibernate my laptop for a longer period of time.

In order to run the project, please execute:
- `npm install`
- `npm run startdev`

Then the dev server will run and HMR should work, but currently it does not work for me. If you enter `localhost:3000`, you will see an error regarding not getting Graphql endpoint. You can define own and provide the path to it in `dev.js`. I used the following repo to create Graphql endpoint: https://github.com/timbofield/graphql-wp. As far as I know, you are not obliged to define this so as to test if HMR works, however, I might miss something.

In the next days, I will try to make the repo more easy to use.

**Comment by gaearon** [comment]
Maybe it would help if you checked whether _the file watcher_ fails (no recompilation messages in the terminal), HMR transport (no network requests for JS files), or runtime fails (HMR succeeded but components were not updated).

Watcher can get a little flaky but it’s nothing we can fix on our side and is completely dependant on Webpack.

**Comment by seoyoochan** [comment]
@gaearon Could my errors be any help for figuring it out?
I am debugging this issue opened by [#332](https://github.com/shakacode/react_on_rails/issues/332) the `react_on_rails` gem community.

Hot reloading works, but whenever I click on an anchor tag to navigate other pages. I get collision issues about React or babel-polyfil ([issue here](https://github.com/shakacode/bootstrap-loader/issues/16))

![img](http://i.imgur.com/mqXYR3B.png)

**Comment by ghost** [comment]
Thank you for all your answers. I noticed that there were no recompilation messages in terminal, so it was not connected with `react-transform-hmr`. I do not know what was the cause, because my hard disk crashed before finding the solution. :broken_heart: Currently, I have SSD and for the same project everything works perfect, so I am closing the issue.
