### ISSUE TITLE
How to disable for server side rendering?

### ISSUE THREAD

**Issue by ronag** [gaearon/react-transform-hmr#7]
When doing server side rendering I get the error: 

`locals[0] does not appear to be a`module`object with Hot Module replacement API enabled`

Which makes sense since `module` only exists in a webpack environment. However, I still need it to run for server side rendering...?

``` json
{
  "env": {
    "development": {
      "plugins": [
        "react-transform"
      ],
      "extra": {
        "react-transform": [{
          "target": "react-transform-hmr",
          "imports": ["react"],
          "locals": ["module"]
        }, {
          "target": "react-transform-catch-errors",
          "imports": ["react", "redbox-react"]
        }]
      }
    },
    "production": {
      "optional": [
        "optimisation.react.constantElements",
        "optimisation.react.inlineElements"
      ]
    }
  }
}
```

**Comment by ronag** [comment]
Turns out this is a breaking change between 0.1.6 and 1.0.0 where missing "hot" starts throwing an error.

**Comment by ronag** [comment]
Use webpack `query` to config only for browser, see https://github.com/rackt/redux/compare/5c8f9ea686...0f45fc1050

**Comment by gaearon** [comment]
For reference, there is discussion in https://github.com/gaearon/react-transform-hmr/issues/5.
