### ISSUE TITLE
componentWillReceiveProps not working correctly in HMR

### ISSUE THREAD

**Issue by joyfeel** [gaearon/react-transform-hmr#70]
I have practice the following snipped code from [React Fundamentals: Component Lifecycle - Updating](https://egghead.io/lessons/react-component-lifecycle-updating?series=react-fundamentals#/tab-code).

```
class App extends React.Component {
  constructor(){
    super();
    this.update = this.update.bind(this);
    this.state = {increasing: false}
  }

  update(){
    ReactDOM.render(
      <App val={this.props.val+1} />,
      document.getElementById('app')
    );
  }
  componentWillReceiveProps(nextProps){
    this.setState({increasing: nextProps.val > this.props.val})
  }

  render(){
    console.log(this.state.increasing)
    return (
      <button onClick={this.update}>
        {this.props.val}
      </button>)
  }
  componentDidUpdate(prevProps, prevState) {
    console.log('prevProps', prevProps)
  }
}

App.defaultProps = { val: 0 }

ReactDOM.render(<App />, document.getElementById('app'));
```

After rendering the button (init with 0 value), and I click it. The `componentWillReceiveProps` function does not triggered at the `first` time!

It get the `nextProps` on the second click.

I have already test the snipped code on `react-transform-boilerplate`.

**Comment by gaearon** [comment]
Good catch! I filed https://github.com/gaearon/react-hot-loader/issues/241 as React Hot Loader 3 supersedes this project.
