### ISSUE TITLE
Error "locals[0] does not appear.." when testing jsx-files with Mocha

### ISSUE THREAD

**Issue by TeemuKoivisto** [gaearon/react-transform-hmr#72]
There is an old issue #5 similar to this but since mine is pretty narrow I thought I'd make a new one instead of opening it again.

So on [my project](https://github.com/ultra-hyper-storm-ohtuprojekti/grappa-front) with babel-preset-react-hmre library enabled in .babelrc as such:

``` JSON
{
  "presets": ["es2015", "react"],
  "env": {
    "development": {
      "presets": ["react-hmre"]
    },
    "testing": {
      "presets": []
    }
  }
}
```

The importing of .jsx -component inside Mocha test with chai produces this:
`Error: locals[0] does not appear to be a module object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using env section in Babel configuration. See the example in README: https://github.`

I don't know the particular reason why the Hot loading causes this but the instructions how to solve the problem are bit inadequate. So as you might have noticed I needed to make another babel environment where the hot module is disabled and the trickier part was setting the NODE_ENV in both Ubuntu/OSX and Windows but I solved it with this hack:

`
"test": "export NODE_ENV=testing|| set NODE_ENV=testing&& mocha --compilers js:babel-core/register --require ./test/testhelper.js \"test/**/*@(.js|.jsx)\"",
`

Not a very clean solution but if there is people experiencing this same problem I hope this helped.

**Comment by stas-vilchik** [comment]
I faced the same issue, and the solution by @TeemuKoivisto works, thanks!

Just a slight note, you don't need to modify `.babel.rc`. Just use any `NODE_ENV` different from `development`.

**Comment by samcorcos** [comment]
+1 Had the same error. @TeemuKoivisto hack fixed it. Thanks!

All I had to do was:

```
"test-integration": "export NODE_ENV=testing && wdio",
"test-unit": "export NODE_ENV=testing && ./node_modules/.bin/karma start"
```

**Comment by gaearon** [comment]
If you keep bumping into this problem I suggest migrating React Hot Loader 3 which doesn’t have this crazy configuration overhead. It was built from the ground up with lessons learned both from React Hot Loader and React Transform. The docs are not there yet but this is a good start: https://github.com/gaearon/react-hot-boilerplate/pull/61. Cheers! I’m closing as this isn’t actionable here.
