### ISSUE TITLE
undefined value static properties outside class

### ISSUE THREAD

**Issue by isman-usoh** [gaearon/react-transform-hmr#75]
undefined value declare static properties set outside class (inside is work)

I use typescript commpile to es6 but static properties outside body class 

.babelrc

```
{
    "presets":["es2015", "stage-0", "react"],
    "plugins":[
        ["react-transform", {
            "transforms":[{
                "transform":"react-transform-hmr",
                "imports":["react"],
                "locals":["module"]
            }]
        }]
    ]
}
```

App.js

```
class App extends Component {
    render() {
        console.log(App.Username); // show undefined 
        return (
            <div>
                <h1>Hello {App.Username}</h1>
            </div>
        );
    }
}
App.Username = "MyUsername";
```

**Comment by gaearon** [comment]
This is fixed [in React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61). This project is deprecated in favor of it, and I don’t intend to fix this here, so I’m closing. However if you send a PR with a fix, I can merge it. Thanks!
