### ISSUE TITLE
Tests fail with: Warning! This doesn't currently work for stateless functional components that were introduced in React 0.14!

### ISSUE THREAD

**Issue by mnemanja** [gaearon/react-transform-hmr#80]
Actually I can confirm that it does work with the stateless functions, but it does not work with the extended class components when trying to run the test where the component is being included.

The error message appears: 

```
Error('locals[0] does not appear to be a `module` object with Hot Module ' + 'replacement API enabled.
```

I am using this [boilerplate](https://github.com/vasanthk/react-es6-webpack-boilerplate).

This is their [.babelrc](https://github.com/vasanthk/react-es6-webpack-boilerplate/blob/master/.babelrc)

**Comment by miraage** [comment]
@gaearon any suggestions how it could be implemented? I need this feature so much and I'm ready to try myself in implementation.

**Comment by gaearon** [comment]
This whole project is deprecated and you should remove it.
