### ISSUE TITLE
Page is not being reloaded after update module name from: react-transform-webpack-hmr to react-transform-hmr

### ISSUE THREAD

**Issue by eriknyk** [gaearon/react-transform-hmr#9]
The message is:

```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
processUpdate.js:60 [HMR]  - ./src/components/Blank.jsx
processUpdate.js:91 [HMR] Reloading page
```

And the page is not being reloaded with the component change :(
It was working well before I made the change on .babelrc, and updating the references of module name

the component is very simple:

``` javascript
import React, { Component, PropTypes } from 'react';
import Form, { Input, Button } from '../../../../core/components/form';
import Panel, { PanelHeading, PanelHeadingTitle, PanelBody, PanelFooter } from '../../../../core/components/Panel'

class Blank extends Component {
    constructor (props, context) {
        super(props, context);

        this.state = {
            canSubmit: false
        };

        this.onValid = this.onValid.bind(this);
        this.onInvalid = this.onInvalid.bind(this);
        this.onSubmit = this.onSubmit.bind(this);
    }

    onValid () {
        this.setState({
            canSubmit: true
        });
    }

    onInvalid () {
        this.setState({
            canSubmit: false
        });
    }

    onSubmit (model) {
        console.log('model', model);
    }

    render () {
        const {name, unreadCount} = this.state;

        return (
            <Panel color="primary">
                <PanelHeadingTitle>Sample Form</PanelHeadingTitle>
                <Form onSubmit={ this.onSubmit } onValid={ this.onValid } onInvalid={ this.onInvalid }>
                    <PanelBody>
                        <Input name="name" placeholder="Your Name" required>Names</Input>
                        <Input name="lastname" placeholder="Your Last Name">Last Name</Input>
                        <Input name="Username" placeholder="Your Username" icon="user">Username</Input>
                        <Input name="email" icon="envelope" validations="isEmail" validationError="This is not a valid email" placeholder="Your Email" required>Email</Input>
                    </PanelBody>
                    <PanelFooter>
                        <Button type="submit" color="primary" disabled={!this.state.canSubmit}>Submit</Button>
                    </PanelFooter>
                </Form>
            </Panel>
        );
    }
}

export default Blank;

```

Any suggestion?
Regards.

**Comment by allanhortle** [comment]
I'm having this same issue. Although for me babel doesn't even rebuild the app. With the hot reloading split across so many modules It's hard to tell where it's actually breaking. 

Related modules that I'm using: 

```
"babel-plugin-react-transform": "^1.0.3",
"react-transform-catch-errors": "^0.1.2",
"react-transform-hmr": "^0.1.4",
"redbox-react": "^1.0.3",
"webpack-dev-middleware": "^1.2.0",
"webpack-hot-middleware": "^2.0.1"
```

**Comment by gaearon** [comment]
Sorry, but I can't help without a reproducible example. Create a project; I'll reopen and take a look!

> With the hot reloading split across so many modules It's hard to tell where it's actually breaking.

Trust me, diagnosing wasn't any easier when it was one module that did everything. :wink:

**Comment by liorbrauer** [comment]
+1 having the same issue, no idea why:

```
[HMR] The following modules couldn't be hot updated: (Full reload needed)
process-update.js:64 [HMR]  - ./app/react/components/LikeBarComponent.cjsx
process-update.js:102 [HMR] Reloading page
```

**Comment by allanhortle** [comment]
I narrowed it somewhat down to something with webpack. I dropped back to version `1.4.13` of webpack and it started working again. Still don't know what the issue is though.

**Comment by darrenscerri** [comment]
+1

**Comment by liorbrauer** [comment]
@allanhortle Hmm, that's very strange. I tried dropping back to that version but I have other dependencies that require a newer version, so no luck there. 

@gaearon I can't provide a reproducible example since it's a part of a private Rails project, but do you have any insight as to under which conditions this kind of error (`The following modules couldn't be hot updated: (Full reload needed)`) can rise? I read somewhere that it might not work on the main component, but I have tried changing and saving small "dumb" components as well without any luck.

**Comment by phaistonian** [comment]
Hello.

Any updates on this one?

**Comment by gaearon** [comment]
This error means that a hot update bubbled up by `import` module tree, and no module handled it. A module only handles hot update with this transform when it contains React component.

So if you have an `index.js` that does not contain a React component, and you edit it, you'll get this warning. It'll make more sense when you read how Webpack Hot Module Replacement works.

**Comment by gaearon** [comment]
(There can't be any update on this. This is just how HMR works. If you have this error, the file you're editing does not contain React components that this transform recognizes, and none of the files importing it, or files importing those files etc, do.)

**Comment by phaistonian** [comment]
Thing is, it is an `index.js` with a React component (actually tried it with multiple components to no avail).

I am sure this is a silly something that's causing this --- or perhaps because I am on babel 6.

**Comment by gaearon** [comment]
I can't help without seeing a project reproducing the issue.
